Switch to bookworm from bullseye for container image
Closes #162 which is earlier attempt to go through backports for which support
in nd-freeze is not yet fixed up. We will get git 1:2.39.2-1.1 instead of now
used 1:2.30.2-1 .  It was needed to overcome an annoying

     error: bogus format in GIT_CONFIG_PARAMETERS

filed in https://git-annex.branchable.com/forum/error__58___bogus_format_in_GIT__95__CONFIG__95__PARAMETERS/
and which should be fine with git starting from 2.34.

Also discovered https://github.com/neurodebian/neurodebian/issues/90 to be added to
nd_freeze. Until then we provide workaround here.

Also this should address fresh FTBFS of datalad/git-annex on linux:

    dpkg-checkbuilddeps: error: Unmet build dependencies: libghc-git-lfs-dev (>= 1.2.0)

see https://github.com/datalad/git-annex/actions/runs/6007358216/job/16293368749