Revert "try to avoid TerminateProcess link error on windows"
This reverts commit 839ec7e26cb3aede8fed37bfd3bb1866f019f19c.

Neither way is working.. The other way failed:

.stack-work\dist\5f9bc736\build\git-annex\git-annex-tmp\Assistant.o:fake:(.text+0x6bb3): undefined reference to `terminatepid'

Seems that winprocess.c is not getting linked in.